### ISSUE TITLE
Fails to decrypt v10 passwords (2024)

### ISSUE THREAD

**Issue by ghost** [Nav3h/Google_Password_Swiper#1]
Title says it all, it's broken

I included every single file as it should and it gives me a decryption failed error.

**Comment by ghost** [comment]
please if anybody has a working model of this i will pay up too 50$ AUD for it at this point holy shit

**Comment by BernKing** [comment]
I am currently working on my own version. But you have open source versions written in python that work if you didn't know.

**Comment by ghost** [comment]
yeah i tried working on a c++ version but soon realised it was about 100 times easier in python and now im just using python for it.

**Comment by BernKing** [comment]
Ye it is but in c++ you have the speed/memory control advantages that allows you to more advanced stuff.

**Comment by ghost** [comment]
soo true, bummer i could never get it to work in c++, tried soo many things that could've been causing it to break, turns out cryptunprotect just hates me on c++ lol

**Comment by BernKing** [comment]
> soo true, bummer i could never get it to work in c++, tried soo many things that could've been causing it to break, turns out cryptunprotect just hates me on c++ lol

Yo, I got my version to work! I have a whole write up explaining the source code, soon I am posting it on my blog (still setting up) and making the repo public. I will hit you up when it is all ready!

**Comment by ghost** [comment]
Thanks man ill make sure to check it out when i get back into c++ cus im working on a few python projects right now as its much simpler to do this sort of stuff lol

**Comment by BernKing** [comment]
Thank you, just finished and made everything public: https://github.com/BernKing/ChromeStealer
The write up is over here: https://bernking.github.io//2024/chrome-stealer/

If you need anything just hit me up

**Comment by ghost** [comment]
Just checked it out and it looks beautiful, you might actually be one of the first people to make a working stealer for chrome without any hassle, im on linux atm but will definitely check it out when im back on windows

**Comment by BernKing** [comment]
Thank you!
